apiVersion: v1
kind: Secret
metadata:
  name: kubemanager-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.groqApiKey | quote }}
  AGENT_TOKEN: {{ .Values.agentToken | quote }}
