apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeeasy.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeeasy.labels" . | nindent 4 }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.groqApiKey | quote }}
  AGENT_TOKEN: {{ .Values.agentToken | quote }}
